server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.0.200:3306/vueadmin
    driverClassName: com.mysql.cj.jdbc.Driver
    username: developer
    password: 'a0909007892'
  security:
    user:
      name: user
      password: root

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

side-project:
  jwt:
    header: Authorization
    expire: 604800 # second
    secret: abcdefghijklmnopqrstuvwxyz12345
