server:
  port: 8080
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/vueadmin
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 'a0909007892'

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

mybatis-plus:
  mapperLocations: "classpath*:/mapper/**/*Mapper.xml"
